In [2]:
%pip install wbgapi

Collecting wbgapi
  Obtaining dependency information for wbgapi from https://files.pythonhosted.org/packages/8f/9e/053111e07789d0dfcbb4ff334b06fdbe6ad8c567be0c6278d0a1781e0793/wbgapi-1.0.14-py3-none-any.whl.metadata
  Downloading wbgapi-1.0.14-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: requests in c:\users\isido\appdata\local\programs\python\python310\lib\site-packages (from wbgapi) (2.32.5)
Collecting PyYAML (from wbgapi)
  Obtaining dependency information for PyYAML from https://files.pythonhosted.org/packages/2a/fa/926c003379b19fca39dd4634818b00dec6c62d87faf628d1394e137354d4/pyyaml-6.0.3-cp310-cp310-win_amd64.whl.metadata
  Downloading pyyaml-6.0.3-cp310-cp310-win_amd64.whl.metadata (2.4 kB)
Collecting tabulate (from wbgapi)
  Obtaining dependency information for tabulate from https://files.pythonhosted.org/packages/99/55/db07de81b5c630da5cbf5c7df646580ca26dfaefa593667fc6f2fe016d2e/tabulate-0.10.0-py3-none-any.whl.metadata
  Downloading tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
     ---------------------------------------- 40.8/40.8 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\isido\appdata\local\programs\python\python310\lib\site-packages (from requests->wbgapi) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\isido\appdata\local\programs\python\python310\lib\site-packages (from requests->wbgapi) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\isido\appdata\local\programs\python\python310\lib\site-packages (from requests->wbgapi) (2.6.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\isido\appdata\local\programs\python\python310\lib\site-packages (from requests->wbgapi) (2025.11.12)
Downloading wbgapi-1.0.14-py3-none-any.whl (36 kB)
Downloading pyyaml-6.0.3-cp310-cp310-win_amd64.whl (158 kB)
   ---------------------------------------- 158.6/158.6 kB 4.8 MB/s eta 0:00:00
Downloading tabulate-0.10.0-py3-none-any.whl (39 kB)
Installing collected packages: tabulate, PyYAML, wbgapi
Successfully installed PyYAML-6.0.3 tabulate-0.10.0 wbgapi-1.0.14
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Análisis de Nexo Energía-Economía**

_Intuición Inicial:_ 
Existe una correlación positiva fuerte entre el desarrollo económico (PIB) y el impacto ambiental ($CO_{2}$). Específicamente se espera encontrar que los países con mayor PIB per cápita tienen mayores emisiones históricas y que en los último años, países desarrollados muestran un "desacople", donde el PIB sigue subiendo pero las emisiones se estabilizan o bajan.

In [ ]:
import pandas as pd
import wbgapi as wb

indicadores = {
    'NY.GDP.PCAP.KD': 'PIB_per_capita',
    'EN.ATM.CO2E.PC': 'CO2_per_capita'
}

paises = ['CHL', 'ARG', 'BRA', 'USA', 'CHN', 'DEU']

data = wb.data.DataFrame(indicadores.keys(), paises, time=range(2000, 2025), numericTimeKeys=True)

df = data.stack().reset_index()

df.columns = ['economy', 'series', 'time', 'value']

df['series'] = df['series'].map(indicadores)

df_final = df.pivot(index=['economy', 'time'], columns='series', values='value').reset_index()

df_final.head()

series economy  time  PIB_per_capita
0          ARG  2000    10631.650364
1          ARG  2001    10051.944846
2          ARG  2002     8861.561993
3          ARG  2003     9545.531941
4          ARG  2004    10302.446532

In [5]:
# 1. Ver una muestra aleatoria para encontrar otros países (como Chile)
print("Muestra de países aleatorios:")
display(df_final.sample(10))

# 2. Verificar que la columna de CO2 realmente existe
print("\nColumnas presentes en tu tabla:")
print(df_final.columns.tolist())

# 3. Ver las últimas filas (donde suelen estar USA o China)
print("\nÚltimas filas del dataset:")
display(df_final.tail())

Muestra de países aleatorios:

series economy  time  PIB_per_capita
121        DEU  2021    44011.019463
100        DEU  2000    35104.130847
12         ARG  2012    13754.425424
127        USA  2002    48729.158644
52         CHL  2002     8810.690527
64         CHL  2014    13285.954036
29         BRA  2004     7258.781017
129        USA  2004    51098.557301
96         CHN  2021    11469.570713
75         CHN  2000     2237.442985

Columnas presentes en tu tabla:
['economy', 'time', 'PIB_per_capita']

Últimas filas del dataset:

series economy  time  PIB_per_capita
145        USA  2020    59194.666517
146        USA  2021    62680.250359
147        USA  2022    63886.131707
148        USA  2023    65186.597724
149        USA  2024    66356.170675

In [6]:
# Diagnóstico: ¿Qué códigos trajo realmente la API?
print("Códigos encontrados en la columna 'series':")
print(df['series'].unique())

# Verificamos si el mapeo funcionó
print("\n¿Cómo quedó la columna 'series' después del map?:")
print(df['series'].head(10))

Códigos encontrados en la columna 'series':
['PIB_per_capita']

¿Cómo quedó la columna 'series' después del map?:
0    PIB_per_capita
1    PIB_per_capita
2    PIB_per_capita
3    PIB_per_capita
4    PIB_per_capita
5    PIB_per_capita
6    PIB_per_capita
7    PIB_per_capita
8    PIB_per_capita
9    PIB_per_capita
Name: series, dtype: object